# Generated by Django 5.0 on 2023-12-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeName', models.CharField(max_length=255)),
                ('coffeeDesc', models.TextField()),
                ('coffeePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coffeeFlavor', models.CharField(max_length=100)),
                ('isWithMarshmello', models.BooleanField(default=False)),
                ('isWithDonuts', models.BooleanField(default=False)),
                ('isAvailable', models.BooleanField(default=True)),
                ('coffeeSize', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
